-- AlterTable
ALTER TABLE "Sku" ADD COLUMN     "clicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "conversion_rate" DECIMAL NOT NULL DEFAULT 0,
ADD COLUMN     "cpc" DECIMAL NOT NULL DEFAULT 0,
ADD COLUMN     "ctr" DECIMAL NOT NULL DEFAULT 0,
ADD COLUMN     "placement" TEXT;
